name = "share-purse-backend"
main = "src/index.ts"
compatibility_date = "2025-01-18"

# compatibility_flags = [ "nodejs_compat" ]

# カスタムドメイン
routes = [
  { pattern = "worker.pair-pay.work", custom_domain = true }
]

[vars]
JWT_SECRET = "local_development_secret_key_2025"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "pairPayDB"
database_id = "8e9e1073-7728-469d-9e83-e83be8bad035"

# [ai]
# binding = "AI"

[observability]
enabled = true
# head_sampling_rate = 1
