name = "share-purse-backend"
main = "src/index.ts"
compatibility_date = "2025-01-18"

# compatibility_flags = [ "nodejs_compat" ]

# カスタムドメイン
routes = [
  { pattern = "worker.pair-pay.work", custom_domain = true }
]

[vars]
# JWT署名用のシークレットキー（本番環境用はCloudflareのダッシュボードで設定）
JWT_SECRET = "local_development_secret_key_2025"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "share-purse-db"
database_id = "dfb91fa4-b9d4-4c95-9d8d-53dd70b39200"

# [ai]
# binding = "AI"

[observability]
enabled = true
# head_sampling_rate = 1
