name = "share-purse-backend-test"
main = "src/index.ts"
compatibility_date = "2025-01-18"

[vars]
JWT_SECRET = "test_environment_secret_key"

[[d1_databases]]
binding = "DB"
database_name = "share-purse-test-db"
database_id = "test"

[observability]
enabled = true