name: E2E Tests

on:
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: |
          npm i
          npm run build:shared

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Create D1 Database
        working-directory: ./backend
        run: |
          npx wrangler d1 execute share-purse-db --local --file=./drizzle/migrations/0000_careful_madame_web.sql

      - name: Start Backend Server
        run: |
          npm run dev -w backend &
        env:
          JWT_SECRET: test_secret_key
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_DATABASE_ID: dfb91fa4-b9d4-4c95-9d8d-53dd70b39200
          CLOUDFLARE_D1_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Run E2E Tests
        run: npm run test:e2e -w frontend
        env:
          CI: true
          NEXT_PUBLIC_BACKEND_URL: http://localhost:8787
