name: E2E Tests (Production)

on:
  workflow_run:
    workflows:
      - Deploy
    types:
      - completed
  pull_request:

jobs:
  e2e-tests-production:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Production E2E Tests
        run: npx playwright test
        env:
          # 環境変数
          PROD_URL: ${{ env.PROD_URL }}
          CI: true
