name: Lint

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js v20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Cache Node Modules
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          backend/node_modules
          frontend/node_modules
          packages/shared/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json', '**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Dependencies
      run: |
        npm ci
        npm run build:shared

    - name: Lint All Packages By Biome
      run: npm run lint
