name: Lint

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js v20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: |
        npm ci
        npm run build:shared

    - name: Shared Package Lint
      run: npm run lint --workspace=packages/shared

    - name: Frontend Lint
      run: npm run lint --workspace=frontend

    - name: Backend Lint
      run: npm run lint --workspace=backend
