name: Lint

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js v22
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          node_modules
          packages/*/node_modules
          frontend/node_modules
          backend/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Dependencies
      run: npm ci

    - name: Shared Package Lint
      run: npm run lint --workspace=packages/shared

    - name: Frontend Lint
      run: npm run lint --workspace=frontend

    - name: Backend Lint
      run: npm run lint --workspace=backend
