name: Test

on:
  pull_request:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js v22
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: install dependencies
      run: npm ci

    - name: Backend Tests
      run: npm run test:ci --workspace=backend

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        directory: ./backend/coverage
        flags: backend
        name: share-purse-backend
